apiVersion: 1

datasources:
- name: MaintenanceActionLog
  org_id: null
  type: elasticsearch
  access: proxy
  database: maintenance_action_log
  url: https://<_MASTER_ESROUTER_HOST_>:<_MASTER_ESROUTER_PORT_>
  basicAuth: true
  withCredentials: true
  basicAuthUser: admin
  secureJsonData:
    basicAuthPassword: "<_ELASTICSEARCH_ADMIN_PASSWORD_>"
  jsonData:
    timeField: actionStartDate
    esVersion: 70
    tlsSkipVerify: true