{
  "id": null,
  "uid": null,
  "orgId": null,
  "name": "TestDS",
  "type": "elasticsearch",
  "typeLogoUrl": "",
  "access": "proxy",
  "url": "http://10.100.0.22:3001",
  "password": "",
  "user": "",
  "database": "titi",
  "basicAuth": true,
  "basicAuthUser": "admin",
  "basicAuthPassword": "admin",
  "withCredentials": true,
  "isDefault": false,
  "jsonData": {
    "timeField" : "timestamp",
    "elasticsearchType": "default",
    "elasticsearchVersion": "70"
  }
}
