apiVersion: 1

datasources:
- name: SMSInternal
  org_id: 1
  type: elasticsearch
  access: proxy
  database: "messagegatewaysmsinternal"
  url: 'http://<_MASTER_ESROUTER_HOST_>:<_MASTER_ESROUTER_PORT_>'
  jsonData:
    timeField: "eventDate"
    esVersion: 70