apiVersion: 1
datasources:
- name: AllJourneyRewards
  org_id: null
  type: elasticsearch
  access: proxy
  database: t*_datacube_journeyrewards-*
  url: 'https://<_MASTER_ESROUTER_HOST_>:<_MASTER_ESROUTER_PORT_>' 
  basicAuth: true
  withCredentials: true
  tlsSkipVerify: true
  basicAuthUser: admin
  secureJsonData:
    basicAuthPassword: "<_ELASTICSEARCH_ADMIN_PASSWORD_>"
  jsonData:
    timeField: timestamp
    esVersion: 70
