apiVersion: 1

datasources:
- name: JourneysMapping
  org_id: 1
  type: elasticsearch
  access: proxy
  database: "mapping_journeys"
  url: 'http://<_MASTER_ESROUTER_HOST_>:<_MASTER_ESROUTER_PORT_>'
  jsonData:
    timeField: "timestamp"
    esVersion: 70