apiVersion: 1
datasources:
- name: SMSAggregated
  org_id: null
  type: elasticsearch
  access: proxy
  database: msgg_indicators_log
  url: 'https://<_MASTER_ESROUTER_HOST_>:<_MASTER_ESROUTER_PORT_>'
  basicAuth: true
  withCredentials: true
  basicAuthUser: admin
  secureJsonData:
    basicAuthPassword: "<_ELASTICSEARCH_ADMIN_PASSWORD_>"
  jsonData:
    timeField: date
    esVersion: 70
    tlsSkipVerify: true
