apiVersion: 1
datasources:
- name: JourneyRewardsMapping
  org_id: null
  type: elasticsearch
  access: proxy
  database: mapping_journeyrewards
  url: 'http://<_MASTER_ESROUTER_HOST_>:<_MASTER_ESROUTER_PORT_>'
  basicAuth: true
  withCredentials: true
  basicAuthUser: admin
  secureJsonData:
    basicAuthPassword: "<_ELASTICSEARCH_ADMIN_PASSWORD_>"
  jsonData:
    timeField: timestamp
    esVersion: 70
