apiVersion: 1

datasources:
- name: AllJourneyTraffic
  org_id: 1
  type: elasticsearch
  access: proxy
  database: "datacube_journeytraffic-*"
  url: 'http://<_MASTER_ESROUTER_HOST_>:<_MASTER_ESROUTER_PORT_>'
  user: "customer"
  secureJsonData:
    password: "ev0lv1ng"
  jsonData:
    timeField: "timestamp"
    esVersion: 70