lowercaseOutputName: true
rules:
  - pattern : kafka.streams<type=stream-metrics, client-id=streams-propensityengine.+-(StreamThread-.+)><>((\w|-)+)
    name: kafka_streams_propensityengine_stream_$2
    labels:
      threadID: "$1"
  - pattern : kafka.streams<type=stream-rocksdb-state-metrics, client-id=streams-propensityengine.+-(StreamThread-.+)><>((\w|-)+)
    name: kafka_streams_propensityengine_rocksdb_$2
    labels:
      threadID: "$1"
  - pattern: "com.evolving.nglm.evolution.*"
