csr-web-<_KEY_>:
  image: ${env.DOCKER_REGISTRY}csr.web:${gui-csr.version}
  environment:
    csr_api_server_path: "<_GUI_HTTP_PROCOTOL_>://<_GUI_CSR_API_FULL_PATH_>"
    csr_fwk_api_server_path: "<_GUI_HTTP_PROCOTOL_>://<_GUI_FWK_API_FULL_PATH_>"
    csr_api_server_path_for_upload_files: "<_GUI_HTTP_PROCOTOL_>://<_GUI_CSR_API_FULL_PATH_>/file/flowupload"
    CSR_DNBO_INSTALL: '${gui.opc.dnbo.display}'
    CSR_NBO_INSTALL: '<_CSR_NBO_INSTALL_>'
    SHOW_CHALLENGES: '<_CSR_SHOW_CHALLENGES_>'
    SHOW_MISSIONS: '<_CSR_SHOW_MISSIONS_>'
    APPROVAL_MODE_ENABLED: '<_APPROVAL_MODE_ENABLED_>'
    DATE_TIME_FORMAT: "<_DATE_TIME_FORMAT_>"
    DATE_TIME_Z_FORMAT: "<_DATE_TIME_Z_FORMAT_>"
    DATE_FORMAT: "<_DATE_FORMAT_>"
    TIME_FORMAT: "<_TIME_FORMAT_>"
    DISPLAY_DATE_TIME_FORMATS: "<_DISPLAY_DATE_TIME_FORMATS_>"
    DISPLAY_DATE_FORMATS: "<_DISPLAY_DATE_FORMATS_>"
    DISPLAY_TIME_FORMATS: "<_DISPLAY_TIME_FORMATS_>"
    TZ: <_DEPLOYMENT_TIMEZONE_>
    CSR_WEB_PORT: <_PORT_>
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUI_CSR_WEB_SERVER_HOST_>
  networks:
    - outside

