csr-api-<_KEY_>:
  image: ${env.DOCKER_REGISTRY}csr.api:${gui-csr.version}
  user: '<_DOCKER_UID_>:<_DOCKER_GID_>'
  environment:
    FwkSettings__AuthorizationBaseUrl: "http://<_GUI_FWK_AUTH_SERVER_HOST_IP_>:<_GUI_FWK_AUTH_SERVER_PORT_>/api"
    FwkSettings__UploadFolder: '/mnt/upload'
    GuiManagerSettings__ApiBaseUrl:  "http://<_GUIMANAGER_HOST_>:<_GUIMANAGER_PORT_>/nglm-guimanager/"
    ConnectionStrings__FwkConnection: 'Server=<_MYSQL_GUI_SERVER_HOST_>;Port=<_MYSQL_GUI_SERVER_PORT_>;Database=dbframework;UID=root;Password=<_MYSQL_ROOT_PASSWORD_>'
    DNBOSettings__DNBO_INSTALL: '${gui.opc.dnbo.display}'
    DNBOSettings__DNBOEngineSettings__ApiBaseUrl: '<_IOM_SERVER_URL_>'
    DNBOSettings__DNBOEngineSettings__SalesChannelId: <_OPC_WEB_SALE_CHANNEL_ID_>
    DNBOSettings__DNBOEngineSettings__ChannelId: <_OPC_WEB_CALLING_CHANNEL_ID_>
    TZ: <_DEPLOYMENT_TIMEZONE_>
    CSR_API_PORT: <_PORT_>
    FWK_SSO_ENABLED: '<_FWK_SSO_ENABLED_>'
    FWK_SSO_AUTHENTICATE: '<_FWK_SSO_AUTHENTICATE_>'
    FWK_SSO_DEFAULT_USER: <_FWK_SSO_DEFAULT_USER_>
  volumes:
    - type: bind
      source: <_NGLM_GUI_RUNTIME_>/csr-api-<_KEY_>/mnt
      target: /mnt
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUI_CSR_API_SERVER_HOST_>
  networks:
    - outside
