csrmockup:
  image: ${env.DOCKER_REGISTRY}csrmockup:${gui-csrmockup.version}
  user: '<_DOCKER_UID_>:<_DOCKER_GID_>'
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUIMANAGER_HOST_>
  networks:
    - outside
