fakesmsc-<_KEY_>:
  image: ${env.DOCKER_REGISTRY}ev-fakesmsc:${fake.smsc.version}
  environment:
    KEY: <_KEY_>
    SMPP_PORT: <_SMPP_PORT_>
    HTTP_PORT: <_HTTP_PORT_>
    TRACE_LEVEL: WARN
  deploy: 
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_HOST_>
  networks:
    - outside

