fakein-<_KEY_>:
  image: ${env.DOCKER_REGISTRY}ev-fakein:${project.name}-${project.version}
  environment:
    PORT: <_PORT_>
    DETERMINISTIC: <_DETERMINISTIC_>
  deploy: 
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_HOST_>
  networks:
    - outside

