fwk-web-<_KEY_>:
  image: ${env.DOCKER_REGISTRY}fwk.web:${gui-fwk.version}
  environment:
    fwk_api_server_path: "<_GUI_HTTP_PROCOTOL_>://<_GUI_FWK_API_FULL_PATH_>"
    fwk_api_server_path_for_upload_files: "<_GUI_HTTP_PROCOTOL_>://<_GUI_FWK_API_FULL_PATH_>/file/flowupload"
    APPROVAL_MODE_ENABLED: '<_APPROVAL_MODE_ENABLED_>'
    DATE_TIME_FORMAT: "<_DATE_TIME_FORMAT_>"
    DATE_TIME_Z_FORMAT: "<_DATE_TIME_Z_FORMAT_>"
    DATE_FORMAT: "<_DATE_FORMAT_>"
    TIME_FORMAT: "<_TIME_FORMAT_>"
    DISPLAY_DATE_TIME_FORMATS: "<_DISPLAY_DATE_TIME_FORMATS_>"
    DISPLAY_DATE_FORMATS: "<_DISPLAY_DATE_FORMATS_>"
    DISPLAY_TIME_FORMATS: "<_DISPLAY_TIME_FORMATS_>"    
    FWK_SHOWVERSION: '<_FWK_SHOWVERSION_>'
    TENANT_ENABLED: '<_FWK_TENANT_ENABLED_>'    
    TZ: <_DEPLOYMENT_TIMEZONE_>
    FWK_WEB_PORT: <_PORT_>
    FWKSETTINGS_SAML2_AUTHENTICATION: '<_FWKSETTINGS_SAML2_AUTHENTICATION_>'
  volumes:
    - type: bind
      source: <_NGLM_GUI_RUNTIME_>/fwk-api-<_KEY_>/mnt
      target: /mnt    
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUI_FWK_WEB_SERVER_HOST_>
  networks:
    - outside
