fwk-api-<_KEY_>:
  image: evolving/fwk.api:${gui-fwk.version}
  user: '<_DOCKER_UID_>:<_DOCKER_GID_>'
  environment:
    AppSettings__AuthorizationBaseUrl: "http://<_GUI_FWK_AUTH_SERVER_HOST_IP_>:<_GUI_FWK_AUTH_SERVER_PORT_>/api"
    FwkSettings__AuthorizationBaseUrl: "http://<_GUI_FWK_AUTH_SERVER_HOST_IP_>:<_GUI_FWK_AUTH_SERVER_PORT_>/api"
    ConnectionStrings__FwkConnection: 'Server=<_GUI_MYSQL_SERVER_HOST_IP_>;Port=<_GUI_MYSQL_SERVER_PORT_>;Database=dbframework;UID=root;Password=<_MYSQL_ROOT_PASSWORD_>'
    FWK_API_PORT: <_PORT_>
  volumes:
    - type: bind
      source: <_NGLM_GUI_RUNTIME_>/fwk-api-<_KEY_>/mnt
      target: /mnt
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUI_FWK_API_SERVER_HOST_>
  networks:
    - outside
