fwk-api:
  image: evolving/fwk.api:${gui-fwk.version}
  user: '<_DOCKER_UID_>:<_DOCKER_GID_>'
  environment:
    AppSettings__AuthorizationBaseUrl: "http://<_GUI_AUTH_HOST_IP_>:<_GUI_AUTH_PORT_>/api"
    FwkSettings__AuthorizationBaseUrl: "http://<_GUI_AUTH_HOST_IP_>:<_GUI_AUTH_PORT_>/api"
    ConnectionStrings__FwkConnection: 'Server=<_GUI_MYSQLDB_HOST_IP_>;Port=<_GUI_MYSQLDB_PORT_>;Database=dbframework;UID=root;Password=<_GUI_MYSQLDB_PASSWORD_>'
  volumes:
    - type: bind
      source: <_NGLM_GUI_RUNTIME_>/fwk-api/mnt
      target: /mnt
  deploy: 
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUI_API_HOST_>
  ports:
    - "<_GUI_API_PORT_>:8084"
  networks:
    - ev-gui-mysql_standard
  depends_on:
    - fwkauth-api
