fwkauth-api:
  image: evolving/fwkauth.api:${gui-fwk.version}
  user: '<_DOCKER_UID_>:<_DOCKER_GID_>'
  volumes:
    - type: bind
      source: <_NGLM_GUI_RUNTIME_>/fwkauth-api/mnt
      target: /mnt
  deploy: 
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUI_AUTH_HOST_>
  ports:
    - "<_GUI_AUTH_PORT_>:8085"
  networks:
    - ev-gui-mysql_standard
