fwkauth-api-<_KEY_>:
  image: evolving/fwkauth.api:${gui-fwk.version}
  user: '<_DOCKER_UID_>:<_DOCKER_GID_>'
  volumes:
    - type: bind
      source: <_NGLM_GUI_RUNTIME_>/fwkauth-api-<_KEY_>/mnt
      target: /mnt
  ports:
    - target: 8045
      published: <_PORT_>
      mode: host
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUI_FWK_AUTH_SERVER_HOST_>
