fwkauth-api-<_KEY_>:
  image: ${env.DOCKER_REGISTRY}fwkauth.api:${gui-fwk.version}
  user: '<_DOCKER_UID_>:<_DOCKER_GID_>'
  environment:   
    Logging__LogLevel__Default: '<_GUI_LOGGING_LOGLEVEL_DEFAULT_>'
    FwkAuthSettings__EnableClientIPAuthorization: '<_FWKAUTHSETTINGS_ENABLECLIENTIPAUTHORIZATION_>'
    FwkAuthSettings__TokenTimeOutInMinutes: '<_FKWAUTHSETTINGS_TOKENTIMEOUTINMINUTES_>'
    Logging__LogLevel__Default: '<_GUI_LOGGING_LOGLEVEL_DEFAULT_>'
    TZ: <_DEPLOYMENT_TIMEZONE_>
    FWK_AUTH_API_PORT: <_PORT_>
  volumes:
    - type: bind
      source: <_NGLM_GUI_RUNTIME_>/fwkauth-api-<_KEY_>/mnt
      target: /mnt
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUI_FWK_AUTH_SERVER_HOST_>
  networks:
    - outside
