gui-links-dashboard-<_KEY_>:
  image: ${env.DOCKER_REGISTRY}ev-gui.dashboardlinks:${gui-links.version}
  environment:
    ELASTICSEARCH_HOST: '<_DL_ELASTICSEARCH_HOST_IP_>'
    ELASTICSEARCH_PORT: '<_DL_ELASTICSEARCH_PORT_>'
    ELASTICSEARCH_USER: 'admin'
    ELASTICSEARCH_PASS: '<_ELASTICSEARCH_ADMIN_PASSWORD_>'
    ELASTICSEARCH_INDEXNAME: 'dashboard_links'
    GUIMANAGER_HOST: "<_GUIMANAGER_HOST_>"
    GUIMANAGER_PORT: <_GUIMANAGER_PORT_>
    GRAFANA_WEB_SERVER_HOST_INTERNAL_IP: "<_GRAFANA_WEB_SERVER_HOST_INTERNAL_IP_>"
    GRAFANA_WEB_SERVER_PORT: <_GRAFANA_FOR_GUI_PORT_>
    GRAFANA_USER: "<_GRAFANA_USER_GUI_>"
    GRAFANA_PASS: "<_GRAFANA_PASSWORD_GUI_>"  
    TZ: <_DEPLOYMENT_TIMEZONE_>
  volumes:
    - type: bind
      source: <_NGLM_GUI_RUNTIME_>
      target: /mnt
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUI_LINKS_SERVER_HOST_>
  networks:
    - outside
  