gui-links-logstash-<_KEY_>:
  image: ${env.DOCKER_REGISTRY}ev-gui.dashboardlinks:${gui-links.version}
  environment:
    ELASTICSEARCH_HOST: '<_MASTER_ESROUTER_HOST_>'
    ELASTICSEARCH_PORT: '<_MASTER_ESROUTER_PORT_>'
    ELASTICSEARCH_ADMIN_USER: 'admin'
    ELASTICSEARCH_ADMIN_PASSWORD: '<_ELASTICSEARCH_ADMIN_PASSWORD_>'
    ELASTICSEARCH_INDEXNAME: 'dashboard_links'
    TZ: <_DEPLOYMENT_TIMEZONE_>
  volumes:
    - type: bind
      source: <_NGLM_GUI_RUNTIME_>
      target: /mnt
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUI_LINKS_SERVER_HOST_>
  networks:
    - outside
