iar-web-<_KEY_>:
  image: ${env.DOCKER_REGISTRY}iar.web:${gui-iar.version}
  environment:
    iar_api_server_path: "http://<_GUI_IAR_API_SERVER_HOST_EXTERNAL_IP_>:<_GUI_IAR_API_SERVER_PORT_>/api/"
    iar_fwk_api_server_path: "http://<_GUI_FWK_API_SERVER_HOST_EXTERNAL_IP_>:<_GUI_FWK_API_SERVER_PORT_>/api/"
    iar_api_server_path_for_upload_files: "http://<_GUI_IAR_API_SERVER_HOST_EXTERNAL_IP_>:<_GUI_IAR_API_SERVER_PORT_>/api/file/flowupload"
    IAR_URL_ELASTICSEARCH_PATH: "http://<_MASTER_ESROUTER_HOST_>:<_MASTER_ESROUTER_PORT_>"
    IAR_URL_KIBANA_PATH: "http://<_MONITORING_HOST_IP_>:<_KIBANA_PORT_>"
    IAR_URL_GRAFANA_PATH: "<_IAR_URL_GRAFANA_PATH_>"
    IAR_URL_OTHERWEB_PATH: "<_IAR_URL_OTHERWEB_PATH_>"
    WEB_URL_ALLOW: "<_WEB_URL_ALLOW_PATH_>"
    TZ: <_DEPLOYMENT_TIMEZONE_>
    IAR_WEB_PORT: <_PORT_>
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUI_IAR_WEB_SERVER_HOST_>
  networks:
    - outside

