iar-web-<_KEY_>:
  image: evolving/iar.web:${gui-iar.version}
  environment:
    iar_api_server_path: "http://<_GUI_IAR_API_SERVER_HOST_EXTERNAL_IP_>:<_GUI_IAR_API_SERVER_PORT_>/api/"
    iar_fwk_api_server_path: "http://<_GUI_FWK_API_SERVER_HOST_EXTERNAL_IP_>:<_GUI_FWK_API_SERVER_PORT_>/api/"
    iar_api_server_path_for_upload_files: "http://<_GUI_IAR_API_SERVER_HOST_EXTERNAL_IP_>:<_GUI_IAR_API_SERVER_PORT_>/api/file/flowupload"
    TZ: <_DEPLOYMENT_TIMEZONE_>
    IAR_WEB_PORT: <_PORT_>
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUI_IAR_WEB_SERVER_HOST_>
  networks:
    - outside

