itm-api-<_KEY_>:
  image: evolving/itm.api:${gui-itm.version}
  user: '<_DOCKER_UID_>:<_DOCKER_GID_>'
  environment:
    FwkSettings__AuthorizationBaseUrl: "http://<_GUI_FWK_AUTH_SERVER_HOST_IP_>:<_GUI_FWK_AUTH_SERVER_PORT_>/api"
    FwkSettings__UploadFolder: '/mnt/upload'
    ConnectionStrings__FwkConnection: 'Server=<_GUI_MYSQL_SERVER_HOST_IP_>;Port=<_GUI_MYSQL_SERVER_PORT_>;Database=dbframework;UID=root;Password=<_MYSQL_ROOT_PASSWORD_>'
    ItmSettings__ITMApiBaseUrl: 'http://<_GUIMANAGER_HOST_>:<_GUIMANAGER_PORT_>/nglm-triggerrule/'
    ItmSettings__DateTimeFormat: 'yyyy-MM-ddTHH:mm:ss:fff+0600'
    ItmSettings__DefaultApplicationUsingTriggers: 'ICDP'
    ItmSettings__TriggerNameStartWith : ''
  volumes:
    - type: bind
      source: <_NGLM_GUI_RUNTIME_>/itm-api-<_KEY_>/mnt
      target: /mnt
  ports:
    - target: 8080
      published: <_PORT_>
      mode: host
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUI_ITM_API_SERVER_HOST_>
