jmr-web-<_KEY_>:
  image: ${env.DOCKER_REGISTRY}jmr.web:${gui-jmr.version}
  environment:
    jmr_api_server_path: "http://<_GUI_JMR_API_SERVER_HOST_EXTERNAL_IP_>:<_GUI_JMR_API_SERVER_PORT_>/api/"
    jmr_fwk_api_server_path: "http://<_GUI_FWK_API_SERVER_HOST_EXTERNAL_IP_>:<_GUI_FWK_API_SERVER_PORT_>/api/"
    jmr_fwk_api_server_path_for_upload_files: "http://<_GUI_FWK_API_SERVER_HOST_EXTERNAL_IP_>:<_GUI_FWK_API_SERVER_PORT_>/api/file/flowupload"
    JMR_URL_ELASTICSEARCH_PATH: "http://<_MASTER_ESROUTER_HOST_>:<_MASTER_ESROUTER_PORT_>"
    JMR_URL_KIBANA_PATH: "http://<_MONITORING_HOST_IP_>:<_KIBANA_PORT_>"
    TEST_ENVIRONMENT: '<_JMR_WEB_TEST_ENVIROMENT_>'
    WEB_URL_ALLOW: "<_WEB_URL_ALLOW_>"
    DIALOG_TEMPLATE_SMS: '<_DIALOG_TEMPLATE_SMS_>'
    DIALOG_TEMPLATE_EMAIL: '<_DIALOG_TEMPLATE_EMAIL_>'
    DIALOG_TEMPLATE_PUSH: '<_DIALOG_TEMPLATE_PUSH_>'
    DIALOG_TEMPLATE_GENERIC: '<_DIALOG_TEMPLATE_GENERIC_>'
    EXPORT_IMPORT_ENABLED: '<_EXPORT_IMPORT_ENABLED_>'
    APPROVAL_MODE_ENABLED: '<_JMR_APPROVAL_MODE_ENABLED_>'
    RECURRENCE_ENABLED: '<_JMR_RECURRENCE_ENABLED_>'
    FIRST_DAY_OF_WEEK: <_FIRST_DAY_OF_WEEK_>
    DAYS_TO_DISPLAY_RECURRENCE_CAMPAIGNS: <_DAYS_TO_DISPLAY_RECURRENCE_CAMPAIGNS_>
    TZ: <_DEPLOYMENT_TIMEZONE_>
    JMR_WEB_PORT: <_PORT_>
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUI_JMR_WEB_SERVER_HOST_>
  networks:
    - outside

