jmr-web-<_KEY_>:
  image: ${env.DOCKER_REGISTRY}jmr.web:${gui-jmr.version}
  environment:
    jmr_api_server_path: "http://<_GUI_JMR_API_SERVER_HOST_EXTERNAL_IP_>:<_GUI_JMR_API_SERVER_PORT_>/api/"
    jmr_fwk_api_server_path: "http://<_GUI_FWK_API_SERVER_HOST_EXTERNAL_IP_>:<_GUI_FWK_API_SERVER_PORT_>/api/"
    jmr_fwk_api_server_path_for_upload_files: "http://<_GUI_FWK_API_SERVER_HOST_EXTERNAL_IP_>:<_GUI_FWK_API_SERVER_PORT_>/api/file/flowupload"
    TZ: <_DEPLOYMENT_TIMEZONE_>
    JMR_WEB_PORT: <_PORT_>
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUI_JMR_WEB_SERVER_HOST_>
  networks:
    - outside

