jmr-web-<_KEY_>:
  image: ${env.DOCKER_REGISTRY}jmr.web:${gui-jmr.version}
  environment:
    jmr_api_server_path: "<_GUI_HTTP_PROCOTOL_>://<_GUI_JMR_API_FULL_PATH_>"
    jmr_fwk_api_server_path: "<_GUI_HTTP_PROCOTOL_>://<_GUI_FWK_API_FULL_PATH_>"
    jmr_fwk_api_server_path_for_upload_files: "<_GUI_HTTP_PROCOTOL_>://<_GUI_JMR_API_FULL_PATH_>/file/flowupload"    
    URL_KIBANA_PATH: "<_GUI_HTTP_PROCOTOL_>://<_GUI_ONSSL_SERVER_HOST_>:<_KIBANA_PORT_ON_SSL_>"
    URL_GRAFANA_PATH: "<_GUI_HTTP_PROCOTOL_>://<_GUI_ONSSL_SERVER_HOST_>"
    URL_GUIMANAGER_API: "http://<_GUIMANAGER_HOST_>:<_GUIMANAGER_PORT_>/nglm-guimanager/"
    GRAFANA_FOR_GUI_PORT: <_GRAFANA_FOR_GUI_PORT_>
    GRAFANA_TENANTS_PORT_START: <_GRAFANA_TENANTS_PORT_START_>    
    WEB_URL_ALLOW: "<_WEB_URL_ALLOW_>"
    JMR_REGEX_DISPLAY: '<_JMR_REGEX_DISPLAY_>'
    TEST_ENVIRONMENT: '<_JMR_WEB_TEST_ENVIROMENT_>'
    CAMPAIGNS_RECURRENCE_ENABLED: '<_JMR_RECURRENCE_ENABLED_>'
    BULK_CAMPAIGNS_RECURRENCE_ENABLED: '<_JMR_BULK_RECURRENCE_ENABLED_>'
    CAMPAIGNS_PRIORITY_ENABLED: '<_JMR_CAMPAIGNS_PRIORITY_ENABLED_>'
    BULK_CAMPAIGNS_PRIORITY_ENABLED: '<_JMR_BULK_CAMPAIGNS_PRIORITY_ENABLED_>'
    JOURNEYS_PRIORITY_ENABLED: '<_JMR_JOURNEYS_PRIORITY_ENABLED_>'
    FIRST_DAY_OF_WEEK: <_FIRST_DAY_OF_WEEK_>
    EXPORT_IMPORT_ENABLED: '<_EXPORT_IMPORT_ENABLED_>'
    DIALOG_TEMPLATE_SMS: '<_DIALOG_TEMPLATE_SMS_>'
    DIALOG_TEMPLATE_EMAIL: '<_DIALOG_TEMPLATE_EMAIL_>'
    DIALOG_TEMPLATE_PUSH: '<_DIALOG_TEMPLATE_PUSH_>'
    DIALOG_TEMPLATE_GENERIC: '<_DIALOG_TEMPLATE_GENERIC_>'
    APPROVAL_MODE_ENABLED: '<_APPROVAL_MODE_ENABLED_>'
    DATE_TIME_FORMAT: "<_DATE_TIME_FORMAT_>"
    DATE_TIME_Z_FORMAT: "<_DATE_TIME_Z_FORMAT_>"
    DATE_FORMAT: "<_DATE_FORMAT_>"
    TIME_FORMAT: "<_TIME_FORMAT_>"
    DISPLAY_DATE_TIME_FORMATS: "<_DISPLAY_DATE_TIME_FORMATS_>"
    DISPLAY_DATE_FORMATS: "<_DISPLAY_DATE_FORMATS_>"
    DISPLAY_TIME_FORMATS: "<_DISPLAY_TIME_FORMATS_>"
    TZ: <_DEPLOYMENT_TIMEZONE_>
    JMR_WEB_PORT: <_PORT_>
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUI_JMR_WEB_SERVER_HOST_>
  networks:
    - outside

