jmr-api-<_KEY_>:
  image: ${env.DOCKER_REGISTRY}jmr.api:${gui-jmr.version}
  user: '<_DOCKER_UID_>:<_DOCKER_GID_>'
  environment:
    FwkSettings__AuthorizationBaseUrl: "http://<_GUI_FWK_AUTH_SERVER_HOST_IP_>:<_GUI_FWK_AUTH_SERVER_PORT_>/api"
    JmrSettings__JMRApiBaseUrl: "http://<_GUIMANAGER_HOST_>:<_GUIMANAGER_PORT_>/nglm-guimanager/"
    FwkSettings__UploadFolder: '/mnt/upload'
    ConnectionStrings__FwkConnection: 'Server=<_MYSQL_GUI_SERVER_HOST_>;Port=<_MYSQL_GUI_SERVER_PORT_>;Database=dbframework;UID=root;Password=<_MYSQL_ROOT_PASSWORD_>'
    JmrSettings__DateTimeFormat: 'yyyy-MM-ddTHH:mm:ss:fff+0600'
    JmrSettings__ApiElasticsearchUrl: "http://<_MASTER_ESROUTER_HOST_>:<_MASTER_ESROUTER_PORT_>/"
    TZ: <_DEPLOYMENT_TIMEZONE_>
    JMR_API_PORT: <_PORT_>
    JmrSettings__EnableApprovalMode: '<_JMRSETTINGS_ENABLEAPPROVALMODE_>'
    JmrSettings__StartWithoutObjective: '<_JMRSETTINGS_STARTWITHOUTOBJECTIVE_>'
    JmrSettings__StartWithoutObjectiveContactPolicy: '<_JMRSETTINGS_STARTWITHOUTOBJECTIVECONTACTPOLICY_>'
    JmrSettings__RaiseAlarmWhenStartWithoutObjective: '<_JMRSETTINGS_RAISEALARMWHENSTARTWITHOUTOBJECTIVE_>'
    JmrSettings__RaiseAlarmWhenStartWithoutObjectiveContactPolicy: '<_JMRSETTINGS_RAISEALARMWHENSTARTWITHOUTOBJECTIVECONTACTPOLICY_>'
    JmrSettings__ByPassContactPolicyIds: '<_JMRSETTINGS__BYPASSCONTACTPOLICYIDS_>'
    JmrSettings__JMRSenderEmail: '<_JMRSETTINGS_JMRSENDEREMAIL_>'
    JmrSettings__JMRSenderName: '<_JMRSETTINGS_JMRSENDERNAME_>'
    JmrSettings__CallBackURLAfterApproveCampain: 'http://<_GUI_JMR_API_SERVER_HOST_>:<_PORT_>/api/campaigns/startAfterApprove'
    JmrSettings__CallBackURLAfterApproveJourney: 'http://<_GUI_JMR_API_SERVER_HOST_>:<_PORT_>/api/journeys/startAfterApprove'
    JmrSettings__CallBackURLAfterApproveBulkCampaign: 'http://<_GUI_JMR_API_SERVER_HOST_>:<_PORT_>/api/bulkCampaigns/startAfterApprove'
    Logging__LogLevel__Default: '<_GUI_LOGGING__LOGLEVEL__DEFAULT_>'
  volumes:
    - type: bind
      source: <_NGLM_GUI_RUNTIME_>/jmr-api-<_KEY_>/mnt
      target: /mnt
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUI_JMR_API_SERVER_HOST_>
  networks:
    - outside
