kafka-lag-exporter:
  image: ${env.DOCKER_REGISTRY}ev-kafkalagexporter:${project.name}-${project.version}  
  depends_on:
    <_ZOOKEEPER_SERVICES_>
    <_BROKER_SERVICES_>
  environment:
    BROKER_SERVERS: <_BROKER_SERVERS_>
    KAFKA_LAG_EXPORTER_PORT: <_KAFKA_LAG_EXPORTER_PORT_>
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_MONITORING_HOST_>
  networks:
    - outside
