lpm-web-<_KEY_>:
  image: ${env.DOCKER_REGISTRY}lpm.web:${gui-lpm.version}
  environment:
    lpm_api_server_path: "http://<_GUI_LPM_API_SERVER_HOST_EXTERNAL_IP_>:<_GUI_LPM_API_SERVER_PORT_>/api/"
    lpm_fwk_api_server_path: "http://<_GUI_FWK_API_SERVER_HOST_EXTERNAL_IP_>:<_GUI_FWK_API_SERVER_PORT_>/api/"
    lpm_api_server_path_for_upload_files: "http://<_GUI_lpm_API_SERVER_HOST_EXTERNAL_IP_>:<_GUI_LPM_API_SERVER_PORT_>/api/file/flowupload"
    LPM_URL_ELASTICSEARCH_PATH: "http://<_MASTER_ESROUTER_HOST_>:<_MASTER_ESROUTER_PORT_>"
    LPM_URL_KIBANA_PATH: "http://<_MONITORING_HOST_IP_>:<_KIBANA_PORT_>"
    WEB_URL_ALLOW: "<_LPM_URL_OTHERWEB_PATH_>"
    TZ: <_DEPLOYMENT_TIMEZONE_>
    LPM_WEB_PORT: <_PORT_>
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUI_LPM_WEB_SERVER_HOST_>
  networks:
    - outside

