opc-web-<_KEY_>:
  image: ${env.DOCKER_REGISTRY}opc.web:${gui-opc.version}
  environment:
    opc_api_server_path: "<_GUI_HTTP_PROCOTOL_>://<_GUI_OPC_API_FULL_PATH_>"
    opc_fwk_api_server_path: "<_GUI_HTTP_PROCOTOL_>://<_GUI_FWK_API_FULL_PATH_>"
    opc_fwk_api_server_path_for_upload_files: "<_GUI_HTTP_PROCOTOL_>://<_GUI_OPC_API_FULL_PATH_>/file/flowupload"
    OPC_DNBO_INSTALL: '${gui.opc.dnbo.display}'
    OPC_DNBO_Scoring_AlwaysAppendOfferObjectiveIDs: 'true'
    URL_KIBANA_PATH: "<_GUI_HTTP_PROCOTOL_>://<_GUI_ONSSL_SERVER_HOST_>:<_KIBANA_PORT_ON_SSL_>"
    URL_GRAFANA_PATH: "<_GUI_HTTP_PROCOTOL_>://<_GUI_ONSSL_SERVER_HOST_>"
    URL_GUIMANAGER_API: "http://<_GUIMANAGER_HOST_>:<_GUIMANAGER_PORT_>/nglm-guimanager/"
    GRAFANA_FOR_GUI_PORT: <_GRAFANA_FOR_GUI_PORT_>
    GRAFANA_TENANTS_PORT_START: <_GRAFANA_TENANTS_PORT_START_>
    WEB_URL_ALLOW: "<_WEB_URL_ALLOW_>"
    OPC_REGEX_DISPLAY: '<_OPC_REGEX_DISPLAY_>'
    OPC_SHOW_SUPPLIER_CATEGORY: '<_OPC_SHOW_SUPPLIER_CATEGORY_>'
    OPC_SHOW_SUPPLIER_LOCATION: '<_OPC_SHOW_SUPPLIER_LOCATION_>'
    OPC_SHOW_RESELLER_CATEGORY: '<_OPC_SHOW_RESELLER_CATEGORY_>'
    OPC_SHOW_RESELLER_LOCATION: '<_OPC_SHOW_RESELLER_LOCATION_>'
    DIALOG_TEMPLATE_SMS: '<_DIALOG_TEMPLATE_SMS_>'
    DIALOG_TEMPLATE_EMAIL: '<_DIALOG_TEMPLATE_EMAIL_>'
    DIALOG_TEMPLATE_PUSH: '<_DIALOG_TEMPLATE_PUSH_>'
    DIALOG_TEMPLATE_GENERIC: '<_DIALOG_TEMPLATE_GENERIC_>'
    EXPORT_IMPORT_ENABLED: '<_OPC_EXPORT_IMPORT_ENABLED_>'
    OPC_OFFER_ONLY_ONE_PRODUCT_OR_VOUCHER: '<_OPC_OFFER_ONLY_ONE_PRODUCT_OR_VOUCHER_>'
    APPROVAL_MODE_ENABLED: '<_APPROVAL_MODE_ENABLED_>'
    DATE_TIME_FORMAT: "<_DATE_TIME_FORMAT_>"
    DATE_TIME_Z_FORMAT: "<_DATE_TIME_Z_FORMAT_>"
    DATE_FORMAT: "<_DATE_FORMAT_>"
    TIME_FORMAT: "<_TIME_FORMAT_>"
    DISPLAY_DATE_TIME_FORMATS: "<_DISPLAY_DATE_TIME_FORMATS_>"
    DISPLAY_DATE_FORMATS: "<_DISPLAY_DATE_FORMATS_>"
    DISPLAY_TIME_FORMATS: "<_DISPLAY_TIME_FORMATS_>"
    TZ: <_DEPLOYMENT_TIMEZONE_>
    OPC_WEB_PORT: <_PORT_>
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUI_OPC_WEB_SERVER_HOST_>
  networks:
    - outside
