opc-api-<_KEY_>:
  image: evolving/opc.api:${gui-opc.version}
  user: '<_DOCKER_UID_>:<_DOCKER_GID_>'
  environment:
    FwkSettings__AuthorizationBaseUrl: 'http://<_GUI_FWK_AUTH_SERVER_HOST_IP_>:<_GUI_FWK_AUTH_SERVER_PORT_>/api'
    GuiManagerSettings__ApiBaseUrl: 'http://<_GUIMANAGER_HOST_>:<_GUIMANAGER_PORT_>/nglm-guimanager/'
    DNBOEngineSettings__ApiBaseUrl: 'http://<_IOM_SERVER_>/Evolving/'
    ConnectionStrings__FwkConnection: 'Server=<_GUI_MYSQL_SERVER_HOST_>;Port=<_GUI_MYSQL_SERVER_PORT_>;Database=dbframework;UID=root;Password=<_MYSQL_ROOT_PASSWORD_>'
    ConnectionStrings__OPCConnection: 'Data Source=<_IOM_DB_HOST_>;Initial Catalog=<_IOM_DB_DATABASE_>;User ID=<_IOM_DB_USER_>;Password=<_IOM_DB_PASSWORD_>'
    Redis__InternalIdRedisConnectionString: '<_SUBSCRIBERIDS_REDIS_SERVER_>,allowAdmin=true,syncTimeout=5000'
  volumes:
    - type: bind
      source: <_NGLM_GUI_RUNTIME_>/opc-api-<_KEY_>/mnt
      target: /mnt
  ports:
    - target: 8080
      published: <_PORT_>
      mode: host
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUI_OPC_API_SERVER_HOST_>
