opc-web-<_KEY_>:
  image: ${env.DOCKER_REGISTRY}opc.web:${gui-opc.version}
  environment:
    opc_api_server_path: "http://<_GUI_OPC_API_SERVER_HOST_EXTERNAL_IP_>:<_GUI_OPC_API_SERVER_PORT_>/api/"
    opc_fwk_api_server_path: "http://<_GUI_FWK_API_SERVER_HOST_EXTERNAL_IP_>:<_GUI_FWK_API_SERVER_PORT_>/api/"
    opc_fwk_api_server_path_for_upload_files: "http://<_GUI_FWK_API_SERVER_HOST_EXTERNAL_IP_>:<_GUI_FWK_API_SERVER_PORT_>/api/file/flowupload"
    TZ: <_DEPLOYMENT_TIMEZONE_>
    OPC_DNBO_INSTALL: '${gui.opc.dnbo.display}'
    OPC_DNBO_Scoring_AlwaysAppendOfferObjectiveIDs: 'true'
    OPC_WEB_PORT: <_PORT_>
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUI_OPC_WEB_SERVER_HOST_>
  networks:
    - outside

