opc-web-<_KEY_>:
  image: ${env.DOCKER_REGISTRY}opc.web:${gui-opc.version}
  environment:
    opc_api_server_path: "http://<_GUI_OPC_API_SERVER_HOST_EXTERNAL_IP_>:<_GUI_OPC_API_SERVER_PORT_>/api/"
    opc_fwk_api_server_path: "http://<_GUI_FWK_API_SERVER_HOST_EXTERNAL_IP_>:<_GUI_FWK_API_SERVER_PORT_>/api/"
    opc_fwk_api_server_path_for_upload_files: "http://<_GUI_OPC_API_SERVER_HOST_EXTERNAL_IP_>:<_GUI_OPC_API_SERVER_PORT_>/api/file/flowupload"    
    OPC_DNBO_INSTALL: '${gui.opc.dnbo.display}'
    OPC_DNBO_Scoring_AlwaysAppendOfferObjectiveIDs: 'true'
    OPC_URL_KIBANA_PATH: 'http://<_MONITORING_HOST_IP_>:<_KIBANA_PORT_>'
    OPC_URL_GRAFANA_PATH: "<_IAR_URL_GRAFANA_PATH_>"
    WEB_URL_ALLOW: "<_WEB_URL_ALLOW_>"
    OPC_REGEX_DISPLAY: '<_OPC_REGEX_DISPLAY_>'
    OPC_SHOW_SUPPLIER_CATEGORY: '<_OPC_SHOW_SUPPLIER_CATEGORY_>'
    OPC_SHOW_SUPPLIER_LOCATION: '<_OPC_SHOW_SUPPLIER_LOCATION_>'
    OPC_SHOW_RESELLER_CATEGORY: '<_OPC_SHOW_RESELLER_CATEGORY_>'
    OPC_SHOW_RESELLER_LOCATION: '<_OPC_SHOW_RESELLER_LOCATION_>'
    DIALOG_TEMPLATE_SMS: '<_DIALOG_TEMPLATE_SMS_>'
    DIALOG_TEMPLATE_EMAIL: '<_DIALOG_TEMPLATE_EMAIL_>'
    DIALOG_TEMPLATE_PUSH: '<_DIALOG_TEMPLATE_PUSH_>'
    DIALOG_TEMPLATE_GENERIC: '<_DIALOG_TEMPLATE_GENERIC_>'
    EXPORT_IMPORT_ENABLED: '<_OPC_EXPORT_IMPORT_ENABLED_>'
    TZ: <_DEPLOYMENT_TIMEZONE_>
    OPC_WEB_PORT: <_PORT_>
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUI_OPC_WEB_SERVER_HOST_>
  networks:
    - outside

