opr-web-<_KEY_>:
  image: ${env.DOCKER_REGISTRY}opr.web:${gui-opr.version}
  environment:
    opr_api_server_path: "<_GUI_HTTP_PROCOTOL_>://<_GUI_OPR_API_FULL_PATH_>"
    opr_fwk_api_server_path: "<_GUI_HTTP_PROCOTOL_>://<_GUI_FWK_API_FULL_PATH_>"
    opr_api_server_path_for_upload_files: "<_GUI_HTTP_PROCOTOL_>://<_GUI_OPR_API_FULL_PATH_>/file/flowupload"
    OPR_GRAFANA_MONITORING: "<_OPR_GRAFANA_MONITORING_>"    
    OPR_URL_KIBANA_PATH: 'http://<_MONITORING_HOST_IP_>:<_KIBANA_PORT_>'
    OPR_URL_GRAFANA_PATH: "<_IAR_URL_GRAFANA_PATH_>"
    WEB_URL_ALLOW: "<_WEB_URL_ALLOW_>"
    TZ: <_DEPLOYMENT_TIMEZONE_>
    OPR_WEB_PORT: <_PORT_>
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUI_OPR_WEB_SERVER_HOST_>
  networks:
    - outside

