opr-web-<_KEY_>:
  image: ${env.DOCKER_REGISTRY}opr.web:${gui-opr.version}
  environment:
    opr_api_server_path: "http://<_GUI_OPR_API_SERVER_HOST_EXTERNAL_IP_>:<_GUI_OPR_API_SERVER_PORT_>/api/"
    opr_fwk_api_server_path: "http://<_GUI_FWK_API_SERVER_HOST_EXTERNAL_IP_>:<_GUI_FWK_API_SERVER_PORT_>/api/"
    opr_api_server_path_for_upload_files: "http://<_GUI_OPR_API_SERVER_HOST_EXTERNAL_IP_>:<_GUI_OPR_API_SERVER_PORT_>/api/file/flowupload"
    TZ: <_DEPLOYMENT_TIMEZONE_>
    OPR_URL_ELASTICSEARCH_PATH: "http://<_MASTER_ESROUTER_HOST_>:<_MASTER_ESROUTER_PORT_>"
    OPR_URL_KIBANA_PATH: "http://<_MONITORING_HOST_IP_>:<_KIBANA_PORT_>"
    OPR_WEB_PORT: <_PORT_>
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUI_OPR_WEB_SERVER_HOST_>
  networks:
    - outside

