prometheus-application:
  image: ${env.DOCKER_REGISTRY}ev-prometheus-application:${project.name}-${project.version}
  user: '<_DOCKER_UID_>:<_DOCKER_GID_>'
  environment:
    MONITORING_HOST: "<_MONITORING_HOST_>"
    PROMETHEUS_APPLICATION_PORT: "<_PROMETHEUS_APPLICATION_PORT_>"
    EVOLUTIONENGINE_PROMETHEUS: "<_EVOLUTIONENGINE_PROMETHEUS_>"
    GUIMANAGER_HOST: "<_GUIMANAGER_HOST_>"
    GUIMANAGER_MONITORING_PORT: "<_GUIMANAGER_MONITORING_PORT_>"
    THIRDPARTYMANAGER_PROMETHEUS: "<_THIRDPARTYMANAGER_PROMETHEUS_>"
    CRITERIAAPI_HOST: "<_CRITERIAAPI_HOST_>"
    CRITERIAAPI_MONITORING_PORT: "<_CRITERIAAPI_MONITORING_PORT_>"
    ALERTMANAGER_PORT: "<_ALERTMANAGER_PORT_>"
    STORAGE_LOCAL_RETENTION: 2160h0m0s
    STORAGE_LOCAL_TARGET_HEAP_SIZE: 6442450944
