  volumes:
    - type: bind
      source: <_NGLM_CORE_RUNTIME_>/prometheus/data-application
      target: /prometheus
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_MONITORING_HOST_>
  configs:
    - source: prometheus-application-config
      target: /etc/prometheus/prometheus.yml.temp
    - source: prometheus-application-alert-rules
      target: /etc/prometheus/prometheus-application-alert.rules.temp

  networks:
    - outside
