sbm-api-<_KEY_>:
  image: ${env.DOCKER_REGISTRY}sbm.api:${gui-sbm.version}
  user: '<_DOCKER_UID_>:<_DOCKER_GID_>'
  environment:
    FwkSettings__UploadFolder: "/mnt/ucgUploadedFiles"
    FwkSettings__AuthorizationBaseUrl: "http://<_GUI_FWK_AUTH_SERVER_HOST_IP_>:<_GUI_FWK_AUTH_SERVER_PORT_>/api"
    SBMSettings__SBMApiBaseUrl: 'http://<_GUIMANAGER_HOST_>:<_GUIMANAGER_PORT_>/nglm-guimanager/'
    SBMSettings__DateTimeFormat: '<_SBM_DATE_TIME_FORMAT_>'
    ConnectionStrings__FwkConnection: 'Server=<_MYSQL_GUI_SERVER_HOST_>;Port=<_MYSQL_GUI_SERVER_PORT_>;Database=dbframework;UID=root;Password=<_MYSQL_ROOT_PASSWORD_>'
    SBMSettings__ApiElasticsearchUrl: "http://<_MASTER_ESROUTER_HOST_>:<_MASTER_ESROUTER_PORT_>/"    
    SBMSettings__ODUser: 'admin'
    SBMSettings__ODPassword: '<_ELASTICSEARCH_ADMIN_PASSWORD_>'
    TZ: <_DEPLOYMENT_TIMEZONE_>
    SBM_API_PORT: <_PORT_>
    Logging__LogLevel__Default: '<_GUI_LOGGING_LOGLEVEL_DEFAULT_>'
  volumes:
    - type: bind
      source: <_NGLM_GUI_RUNTIME_>/sbm-api-<_KEY_>/mnt
      target: /mnt
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUI_SBM_API_SERVER_HOST_>
  networks:
    - outside
