stg-web-<_KEY_>:
  image: ${env.DOCKER_REGISTRY}stg.web:${gui-stg.version}
  environment:
    stg_api_server_path: "<_GUI_HTTP_PROCOTOL_>://<_GUI_STG_API_FULL_PATH_>"
    stg_fwk_api_server_path: "<_GUI_HTTP_PROCOTOL_>://<_GUI_FWK_API_FULL_PATH_>"
    stg_api_server_path_for_upload_files: "<_GUI_HTTP_PROCOTOL_>://<_GUI_STG_API_FULL_PATH_>/file/flowupload"    
    EXPORT_IMPORT_ENABLED: '<_STG_EXPORT_IMPORT_ENABLED_>'
    STG_REGEX_DISPLAY: '<_STG_REGEX_DISPLAY_>'
    CUSTOM_CRITERIA_ENABLED: '<_STG_CUSTOM_CRITERIA_ENABLED_>'
    NOTIFICATION_MANAGER_ENABLED: '<_STG_NOTIFICATION_MANAGER_ENABLED_>'  
    APPROVAL_MODE_ENABLED: '<_APPROVAL_MODE_ENABLED_>'
    AVAILABLE_VALUES_ENABLED: '<_STG_AVAILABLE_VALUES_ENABLED_>'
    DATE_TIME_FORMAT: "<_DATE_TIME_FORMAT_>"
    DATE_TIME_Z_FORMAT: "<_DATE_TIME_Z_FORMAT_>"
    DATE_FORMAT: "<_DATE_FORMAT_>"
    TIME_FORMAT: "<_TIME_FORMAT_>"
    DISPLAY_DATE_TIME_FORMATS: "<_DISPLAY_DATE_TIME_FORMATS_>"
    DISPLAY_DATE_FORMATS: "<_DISPLAY_DATE_FORMATS_>"
    DISPLAY_TIME_FORMATS: "<_DISPLAY_TIME_FORMATS_>"
    DIALOG_TEMPLATE_SMS: '<_DIALOG_TEMPLATE_SMS_>' 
    DIALOG_TEMPLATE_EMAIL: '<_DIALOG_TEMPLATE_EMAIL_>' 
    DIALOG_TEMPLATE_PUSH: '<_DIALOG_TEMPLATE_PUSH_>'  
    DIALOG_TEMPLATE_GENERIC: '<_DIALOG_TEMPLATE_GENERIC_>'
    TZ: <_DEPLOYMENT_TIMEZONE_>
    STG_WEB_PORT: <_PORT_>
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUI_STG_WEB_SERVER_HOST_>
  networks:
    - outside

