stg-web-<_KEY_>:
  image: ${env.DOCKER_REGISTRY}stg.web:${gui-stg.version}
  environment:
    stg_api_server_path: "http://<_GUI_STG_API_SERVER_HOST_EXTERNAL_IP_>:<_GUI_STG_API_SERVER_PORT_>/api/"
    stg_fwk_api_server_path: "http://<_GUI_FWK_API_SERVER_HOST_EXTERNAL_IP_>:<_GUI_FWK_API_SERVER_PORT_>/api/"
    stg_api_server_path_for_upload_files: "http://<_GUI_STG_API_SERVER_HOST_EXTERNAL_IP_>:<_GUI_STG_API_SERVER_PORT_>/api/file/flowupload"
    DIALOG_TEMPLATE_SMS: '<_DIALOG_TEMPLATE_SMS_>' 
    DIALOG_TEMPLATE_EMAIL: '<_DIALOG_TEMPLATE_EMAIL_>' 
    DIALOG_TEMPLATE_PUSH: '<_DIALOG_TEMPLATE_PUSH_>'  
    DIALOG_TEMPLATE_GENERIC: '<_DIALOG_TEMPLATE_GENERIC_>'
    EXPORT_IMPORT_ENABLED: '<_STG_EXPORT_IMPORT_ENABLED_>'
    STG_REGEX_DISPLAY: '<_STG_REGEX_DISPLAY_>'
    CUSTOM_CRITERIA_ENABLED: <_STG_CUSTOM_CRITERIA_ENABLED_>
    TZ: <_DEPLOYMENT_TIMEZONE_>
    STG_WEB_PORT: <_PORT_>
  deploy:
    restart_policy:
      condition: <_DOCKER_RESTART_POLICY_>
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_GUI_STG_WEB_SERVER_HOST_>
  networks:
    - outside

