#  profileengine jmx config for prometheus 
#
lowercaseOutputName: true
rules:
  - pattern : com.evolving.nglm.evolution<type=ProfileEngine, name=streams-profileengine, profileEvent=(.+)><>ProfileEventCount
    name: evolving_nglm_profileengine_profileevent_total
    labels:
      profileEvent: "$1"
    type: COUNTER
  - pattern : com.evolving.nglm.evolution<type=ProfileEngine, name=streams-profileengine><>(\w+)(Count)
    name: evolving_nglm_profileengine_$1_total
    type: COUNTER
  - pattern : kafka.streams<type=stream-metrics, client-id=streams-profileengine.+-(StreamThread-.+)><>((\w|-)+)
    name: kafka_streams_profileengine_stream_$2
    labels:
      threadID: "$1"
  - pattern : kafka.streams<type=stream-rocksdb-state-metrics, client-id=streams-profileengine.+-(StreamThread-.+)><>((\w|-)+)
    name: kafka_streams_profileengine_rocksdb_$2
    labels:
      threadID: "$1"
