nbo-to-redis-<_KEY_>:
  image: evolving/ev-nbo-to-redis:${nbo-to-redis.version}
  user: '<_DOCKER_UID_>:<_DOCKER_GID_>'
  environment:
    KAFKA_BOOTSTRAP_SERVERS: <_BROKER_SERVERS_>
    KAFKA_CONSUMER_GROUP_ID: <_TOPIC_>-group
    KAFKA_TOPIC: <_TOPIC_>
    REDIS_HOST: <_IOMCACHE_REDIS_SERVER_HOST_>
    REDIS_PORT: <_IOMCACHE_REDIS_SERVER_PORT_>
    REDIS_DATABASE: <_REDIS_DATABASE_>
    TZ: <_DEPLOYMENT_TIMEZONE_>
  volumes:
    - type: bind
      source: <_NGLM_NBO_TO_REDIS_RUNTIME_>/nbo-to-redis-<_KEY_>/logs
      target: /app/logs
  deploy:
    restart_policy:
      condition: any
      delay: 5s
      max_attempts: 3
      window: 120s
    mode: replicated
    replicas: 1
    placement:
      constraints:
        - engine.labels.hostname == <_HOST_>
  networks:
    - outside
